In [4]:
import numpy as np
import pandas as pd
from scipy.sparse.linalg import svds
from scipy.linalg import qr

In [3]:
small_em = pd.read_csv('error_matrix_small.csv', index_col=0).values

In [5]:
def pivoted_qr(A):
    return qr(A, pivoting=True)[2]

In [6]:
def pca(A, rank):
    # rank = approx_rank(A)
    col_stdev = np.std(A, axis=0)
    U,s,Vt = svds(A, k=rank)
    Sigma_sqrt = np.diag(np.sqrt(s))
    X = np.matrix.transpose(np.dot(U, Sigma_sqrt))
    Y = np.dot(np.dot(Sigma_sqrt, Vt), np.diag(col_stdev))
    return X,Y,Vt

In [7]:
X,Y,Vt = pca(small_em, 9)

In [9]:
pivoted_qr(small_em)

array([30, 12, 29,  0, 34, 33, 18, 28, 10, 32, 14, 11,  8, 22, 35,  5,  6,
       37, 19, 31, 21,  1,  9,  7, 27,  3, 36, 23, 17,  4, 26,  2, 15, 38,
       20, 16, 25, 13, 24], dtype=int32)

In [8]:
pivoted_qr(Y)

array([30, 12, 34, 33, 29, 18,  0, 13, 38,  9, 10, 11,  1,  7, 14, 15, 16,
       17,  5, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,  4,  6, 31, 32,  3,
        2, 35, 36, 37,  8], dtype=int32)

In [10]:
pivoted_qr(Vt)

array([12, 33, 34, 30, 29,  0, 18, 38, 13,  9, 10, 11,  5,  8, 14, 15, 16,
       17,  6, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,  4,  3, 31, 32,  1,
        2, 35, 36, 37,  7], dtype=int32)

In [11]:
pivoted_qr(np.array([[1,2],[2,4]]))

array([1, 0], dtype=int32)

In [12]:
pivoted_qr(np.array([[2,1],[4,2]]))

array([0, 1], dtype=int32)